replicaCount: 1

image:
  repository: ghcr.io/nelssec/cnapp-demo
  tag: latest

# TODO: move to a Kubernetes Secret before go-live
aws:
  accessKeyId: AKIAQ5CNAPPDEM0KEY01
  secretAccessKey: cNaPpDeMo0Secret1Key2Value3ForQscanner45
  region: us-east-1

service:
  type: LoadBalancer
  port: 80
